name: Maven Build and Test
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: conference
        ports:
          - 5432/tcp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven

      - name: Rewrite environment variables to application-test.properties
        run: |
          echo "spring.datasource.url=jdbc:postgresql://postgres:5432/conference" >> src/main/resources/application-test.properties
          echo "spring.datasource.username=postgres" >> src/main/resources/application-test.properties
          echo "spring.datasource.password=postgres" >> src/main/resources/application-test.properties

      - name: Build with Maven
        run: mvn package --batch-mode

      - name: Test with Maven
        run: mvn test --batch-mode