name: Maven Build and Test
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: conference
        ports:
          - 5432/tcp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package --batch-mode

      - name: Test with Maven
        run: mvn test --batch-mode
        with:
          env:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/conference
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres